// This file is auto-generated by Convex
// Add the generated API types for the assessments module

declare const api: {
  assessments: {
    create: any;
    list: any;
    getById: any;
    updateStatus: any;
    getByStatus: any;
    getByCustomerEmail: any;
  };
};

export { api };
